motors:
  - { id: m1, direction: cw, pin: 22 }
  - { id: m2, direction: ccw, pin: 17 }
  - { id: m3, direction: ccw, pin: 18 }
  - { id: m4, direction: cw, pin: 23 }
  - { id: m5, direction: cw, pin: 27 }
  - { id: m6, direction: ccw, pin: 24 }